Longer auth time

diff --git a/.github/workflows/helm-testing.yml b/.github/workflows/helm-testing.yml
--- a/.github/workflows/helm-testing.yml
+++ b/.github/workflows/helm-testing.yml
@@ -84,7 +84,7 @@ jobs:
       - name: Authenticate
         run: |
           delay=1
-          for i in {1..5}; do
+          for i in {1..8}; do
             delay=$((delay * 2))
             RESPONSE=$(curl -s -k -X POST https://ui.oasis.local/api/access_token/ \
               -H "Content-Type: application/json" \
@@ -99,6 +99,11 @@ jobs:
             fi
             sleep $delay
           done
+
+          if [[ -z "$TOKEN" || "$TOKEN" == "null" ]]; then
+            echo "Failed to retrieve a valid token after retries"
+            exit 1
+          fi
 
       - name: Create Portfolio
         run: |
@@ -205,7 +210,7 @@ jobs:
               -d '{"username": "admin", "password": "password"}' | jq -r '.access_token')
           }
           delay=5
-          for i in {1..10}; do
+          for i in {1..20}; do
             delay=$((delay * 2))
             if ((delay > 30)); then delay=30; fi
             RESPONSE=$(curl -s -k -X GET https://ui.oasis.local/api/v1/analyses/$ANALYSIS_ID/ \
